[package]
name = "reth-stages"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = "Staged syncing primitives used in reth."

[package.metadata.cargo-udeps.ignore]
normal = [
    # Used for diagrams in docs
    "aquamarine"
]

[dependencies]
# reth libs
reth-primitives = { path = "../primitives" }
reth-interfaces = { path = "../interfaces" }
reth-executor = { path = "../executor" }
reth-rlp = { path = "../rlp" }
reth-db = { path = "../storage/db" }
reth-provider = { path = "../storage/provider" }
reth-metrics-derive = { path = "../metrics/metrics-derive" }

# async
tokio = { version = "1.21.2", features = ["sync"] }
tokio-stream = "0.1.10"
async-trait = "0.1.57"
futures-util = "0.3.25"

# observability
tracing = "0.1.36"
metrics = "0.20.1"

# misc
serde = { version = "1.0", optional = true }
thiserror = "1.0.37"
aquamarine = "0.2.1"
itertools = "0.10.5"
rayon = "1.6.0"

# trie
cita_trie = "4.0.0"
hasher = "0.1.4"

# arbitrary utils
arbitrary = { version = "1.1.7", features = ["derive"], optional = true }
proptest = { version = "1.0", optional = true }

[dev-dependencies]
# reth
reth-db = { path = "../storage/db", features = ["test-utils", "mdbx"] }
reth-interfaces = { path = "../interfaces", features = ["test-utils"] }
reth-downloaders = { path = "../net/downloaders" }
reth-eth-wire = { path = "../net/eth-wire" }                            # TODO(onbjerg): We only need this for [BlockBody]
tokio = { version = "*", features = ["rt", "sync", "macros"] }
tempfile = "3.3.0"
assert_matches = "1.5.0"
rand = "0.8.5"
paste = "1.0"

# arbitrary utils
arbitrary = { version = "1.1.7", features = ["derive"] }
proptest = { version = "1.0" }

# trie
reth-staged-sync = { path = "../staged-sync" }
triehash = "0.8"

[features]
default = ["serde"]
serde = ["dep:serde"]
